### ISSUE TITLE
trifecta-ui-0.19.0 can't connect to Kafka brokers

### ISSUE THREAD

**Issue by nobusue** [ldaniels528/trifecta#18]
I'm trying to use new trifecta-ui, but it doesn't work.

It seems to be able to connect to ZooKeeper, but fails to connect Kafka brokers. From console log, /api/topics/details returns 500.

  15422 [ForkJoinPool-2-worker-5] INFO  application - GET /api/topics/details ~> 500 [2316.9 ms]

Detailed logs as follows:

$ bin/trifecta_ui 
241  [main] WARN  application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
1034 [application-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
1043 [main] INFO  play.api.libs.concurrent.ActorSystemProvider - Starting application default Akka system: application
1131 [main] INFO  application - Application has started
1144 [main] INFO  play.api.Play$ - Application started (Prod)
1279 [main] INFO  play.core.server.NettyServer$ - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
3581 [application-akka.actor.default-dispatcher-4] INFO  application - Registering new SSE session '815078639a1a464895cca9f58658ca0f'...
3617 [application-akka.actor.default-dispatcher-2] WARN  application - application.conf @ file:/Users/nobusue/petadata/trifecta/trifecta_ui-0.19.0/conf/application.conf: 8: application.secret is deprecated, use play.crypto.secret instead
3885 [ForkJoinPool-2-worker-7] INFO  application - GET /api/sse/connect ~> 200 [358.7 ms]
13107 [application-akka.actor.default-dispatcher-4] INFO  application - Loading Trifecta configuration...
13107 [application-akka.actor.default-dispatcher-4] INFO  application - Starting Zookeeper client...
13109 [application-akka.actor.default-dispatcher-7] INFO  com.github.ldaniels528.trifecta.actors.ReactiveEventsActor - Preparing streaming consumer updates...
13122 [application-akka.actor.default-dispatcher-8] INFO  com.github.ldaniels528.trifecta.actors.ReactiveEventsActor - Preparing streaming topic updates...
13122 [application-akka.actor.default-dispatcher-8] INFO  akka.actor.DeadLetterActorRef - Message [akka.actor.LightArrayRevolverScheduler$$anon$2] from Actor[akka://application/user/$b#-1990922494] to Actor[akka://application/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
13124 [application-akka.actor.default-dispatcher-3] INFO  akka.actor.DeadLetterActorRef - Message [akka.actor.LightArrayRevolverScheduler$$anon$2] from Actor[akka://application/user/$b#-1990922494] to Actor[akka://application/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
13171 [application-akka.actor.default-dispatcher-4] INFO  org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting
13218 [application-akka.actor.default-dispatcher-3] INFO  application - Registering new SSE session '98b7197104754b1290013f30129455c6'...
13222 [ForkJoinPool-2-worker-3] INFO  application - GET /api/sse/connect ~> 200 [12.1 ms]
13469 [application-akka.actor.default-dispatcher-4-EventThread] INFO  org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED
14907 [ForkJoinPool-2-worker-5] INFO  application - GET /api/zookeeper/path?path=/ ~> 200 [1616.2 ms]
14920 [ForkJoinPool-2-worker-5] INFO  application - GET /api/zookeeper/info?path=/ ~> 200 [1629.3 ms]
log4j:WARN No appenders could be found for logger (kafka.consumer.SimpleConsumer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
15422 [ForkJoinPool-2-worker-5] INFO  application - GET /api/topics/details ~> 500 [2316.9 ms]
28265 [application-akka.actor.default-dispatcher-7] ERROR akka.dispatch.TaskInvocation - Error communicating with Broker [ip-10-0-129-11.us-west-1.compute.internal:9092] Reason: null
com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$VxKafkaException: Error communicating with Broker [ip-10-0-129-11.us-west-1.compute.internal:9092] Reason: null
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$io$kafka$KafkaMicroConsumer$$getTopicMetadata$1.apply(KafkaMicroConsumer.scala:612) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$io$kafka$KafkaMicroConsumer$$getTopicMetadata$1.apply(KafkaMicroConsumer.scala:603) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.commons.helpers.ResourceHelper$AutoClose$.use$extension(ResourceHelper.scala:16) ~[com.github.ldaniels528.commons-helpers_2.11-0.1.2.jar:0.1.2]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$.com$github$ldaniels528$trifecta$io$kafka$KafkaMicroConsumer$$getTopicMetadata(KafkaMicroConsumer.scala:603) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$getTopicList$1.apply(KafkaMicroConsumer.scala:456) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$getTopicList$1.apply(KafkaMicroConsumer.scala:455) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$.getTopicList(KafkaMicroConsumer.scala:455) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.trifecta.controllers.KafkaRestFacade.getTopicDeltas(KafkaRestFacade.scala:431) ~[com.github.ldaniels528.trifecta_ui-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.trifecta.actors.ReactiveEventsActor$$anonfun$com$github$ldaniels528$trifecta$actors$ReactiveEventsActor$$startStreamingTopicUpdates$1.apply$mcV$sp(ReactiveEventsActor.scala:62) ~[com.github.ldaniels528.trifecta_ui-0.19.0.jar:0.19.0]
	at akka.actor.Scheduler$$anon$5.run(Scheduler.scala:79) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: java.nio.channels.ClosedChannelException: null
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110) ~[org.apache.kafka.kafka_2.11-0.9.0.0.jar:na]
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:98) ~[org.apache.kafka.kafka_2.11-0.9.0.0.jar:na]
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) ~[org.apache.kafka.kafka_2.11-0.9.0.0.jar:na]
	at kafka.consumer.SimpleConsumer.send(SimpleConsumer.scala:111) ~[org.apache.kafka.kafka_2.11-0.9.0.0.jar:na]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$io$kafka$KafkaMicroConsumer$$getTopicMetadata$1$$anonfun$17.apply(KafkaMicroConsumer.scala:606) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$io$kafka$KafkaMicroConsumer$$getTopicMetadata$1$$anonfun$17.apply(KafkaMicroConsumer.scala:607) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at com.github.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$io$kafka$KafkaMicroConsumer$$getTopicMetadata$1.apply(KafkaMicroConsumer.scala:604) ~[com.github.ldaniels528.trifecta_cli-0.19.0.jar:0.19.0]
	... 17 common frames omitted

**Comment by nobusue** [comment]
Sorry, this is due to my settings. (Can't resolve EC2 internal hostname)
I've modified /etc/hosts and resolved.

**Comment by ldaniels528** [comment]
I use Microsoft Azure, and it resolves many of these types of issues by default. For free you get a human readable DNS name like "skilldepth.cloudapp.net".

**Comment by cyrilmathew** [comment]
In the UI Im not getting the brokers listed

In the logs:
2018-02-26 14:59:01,235 [INFO] from application in ForkJoinPool-2-worker-7 - GET /api/topics/details ~> 200 [122840.8 ms]
2018-02-26 14:59:18,903 [INFO] from application in ForkJoinPool-2-worker-7 - GET /api/topics/details ~> 200 [119170.4 ms]

Its taking huge time...Is that the issue? And is there any fix on this?
<img width="1030" alt="screen shot 2018-02-26 at 7 26 36 pm" src="https://user-images.githubusercontent.com/30928292/36677728-f3771258-1b34-11e8-8164-d41958eaee0d.png">
