### ISSUE TITLE
Error in communication with broker

### ISSUE THREAD

**Issue by nageshshenoy** [ldaniels528/trifecta#24]
When I try to execute the jar file, getting following error

Trifecta v0.20.0
log4j:WARN No appenders could be found for logger (com.github.ldaniels528.trifecta.TrifectaShell$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$VxKafkaException: Error communicating with Broker [kafka03:9092] Reason: null
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$modules$kafka$KafkaMicroConsumer$$getTopicMetadata$1.apply(KafkaMicroConsumer.scala:655)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$modules$kafka$KafkaMicroConsumer$$getTopicMetadata$1.apply(KafkaMicroConsumer.scala:646)
        at com.github.ldaniels528.commons.helpers.ResourceHelper$AutoClose$.use$extension(ResourceHelper.scala:16)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$.com$github$ldaniels528$trifecta$modules$kafka$KafkaMicroConsumer$$getTopicMetadata(KafkaMicroConsumer.scala:646)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$getTopicList$1.apply(KafkaMicroConsumer.scala:499)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$getTopicList$1.apply(KafkaMicroConsumer.scala:498)
        at scala.Option.map(Option.scala:146)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$.getTopicList(KafkaMicroConsumer.scala:498)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaCliFacade.getTopics(KafkaCliFacade.scala:228)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaModule.getTopics(KafkaModule.scala:746)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaModule$$anonfun$getCommands$30.apply(KafkaModule.scala:111)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaModule$$anonfun$getCommands$30.apply(KafkaModule.scala:111)
        at com.github.ldaniels528.trifecta.TxRuntimeContext$$anonfun$interpretCommandLine$1$$anonfun$apply$2.apply(TxRuntimeContext.scala:176)
        at com.github.ldaniels528.trifecta.TxRuntimeContext$$anonfun$interpretCommandLine$1$$anonfun$apply$2.apply(TxRuntimeContext.scala:170)
        at scala.Option.map(Option.scala:146)
        at com.github.ldaniels528.trifecta.TxRuntimeContext$$anonfun$interpretCommandLine$1.apply(TxRuntimeContext.scala:170)
        at scala.util.Try$.apply(Try.scala:192)
        at com.github.ldaniels528.trifecta.TxRuntimeContext.interpretCommandLine(TxRuntimeContext.scala:156)
        at com.github.ldaniels528.trifecta.TxRuntimeContext.interpret(TxRuntimeContext.scala:111)
        at com.github.ldaniels528.trifecta.TrifectaShell$TrifectaConsole.execute(TrifectaShell.scala:90)
        at com.github.ldaniels528.trifecta.TrifectaShell$.main(TrifectaShell.scala:70)
        at com.github.ldaniels528.trifecta.TrifectaShell.main(TrifectaShell.scala)
Caused by: java.nio.channels.ClosedChannelException
        at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
        at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:98)
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
        at kafka.consumer.SimpleConsumer.send(SimpleConsumer.scala:111)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$modules$kafka$KafkaMicroConsumer$$getTopicMetadata$1$$anonfun$20.apply(KafkaMicroConsumer.scala:649)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$modules$kafka$KafkaMicroConsumer$$getTopicMetadata$1$$anonfun$20.apply(KafkaMicroConsumer.scala:650)
        at scala.util.Try$.apply(Try.scala:192)
        at com.github.ldaniels528.trifecta.modules.kafka.KafkaMicroConsumer$$anonfun$com$github$ldaniels528$trifecta$modules$kafka$KafkaMicroConsumer$$getTopicMetadata$1.apply(KafkaMicroConsumer.scala:647)
        ... 21 more
Runtime error: Error communicating with Broker [kafka03:9092] Reason: null

**Comment by ldaniels528** [comment]
Did this error happen upon connecting? Or after invoking a specific command?

**Comment by nageshshenoy** [comment]
Observed this immediately after invoking the jar file

**Comment by ldaniels528** [comment]
I just uploaded a new release. Try that and let me know if you any the same issue.

**Comment by ldaniels528** [comment]
I've uploaded a new version (v0.21.0) that I believe will fix your problem.

**Comment by ldaniels528** [comment]
Are you still having issues?
