### ISSUE TITLE
REPL Console exists with error

### ISSUE THREAD

**Issue by Nagshenoy89** [ldaniels528/trifecta#25]
Executed jar file and observed that REPL console exits with following error

java -jar "c:\Program Files\trifecta\trifecta_cli_0.20.0.bin.jar"
Trifecta v0.20.0
log4j:WARN No appenders could be found for logger (com.github.ldaniels528.trifecta.TrifectaShell$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Type 'help' (or '?') to see the list of available commands
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at scala.tools.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:261)
        at scala.tools.jline.WindowsTerminal.init(WindowsTerminal.java:96)
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:96)
        at scala.tools.jline.TerminalFactory.get(TerminalFactory.java:154)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:87)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:134)
        at com.github.ldaniels528.trifecta.TrifectaShell$TrifectaConsole.shell(TrifectaShell.scala:123)
        at com.github.ldaniels528.trifecta.TrifectaShell$.main(TrifectaShell.scala:67)
        at com.github.ldaniels528.trifecta.TrifectaShell.main(TrifectaShell.scala)
===============================================================================
Following version of java is used
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode)

**Comment by ldaniels528** [comment]
I just uploaded a new release. Try that and let me know if you any the same issue.

**Comment by ldaniels528** [comment]
Looks like your problem is Windows specific:

https://bukkit.org/threads/cb-2190-startup-error-java-lang-noclassdeffounderror.76218/

And unfortunately my development and testing has been Mac OS X and Linux; however, I will setup a Windows VM and test it there. I believe the problem should be easy to reproduce and fix. I'll just disable the console code when running on Windows.

**Comment by ldaniels528** [comment]
I've uploaded a new version (v0.21.0) that I believe will fix your problem.

**Comment by nageshshenoy** [comment]
Verified with latest version v0.21.0, still getting some error in windows environment
C:\Program Files\trifecta>java -jar trifecta_cli_0.21.0.bin.jar
Trifecta v0.21.0
log4j:WARN No appenders could be found for logger (com.github.ldaniels528.trifecta.TrifectaShell$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Type 'help' (or ?) to see the list of available commands
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at scala.tools.jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:261)
        at scala.tools.jline.WindowsTerminal.init(WindowsTerminal.java:96)
        at scala.tools.jline.TerminalFactory.create(TerminalFactory.java:96)
        at scala.tools.jline.TerminalFactory.get(TerminalFactory.java:154)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:87)
        at scala.tools.jline.console.ConsoleReader.<init>(ConsoleReader.java:134)
        at com.github.ldaniels528.trifecta.TrifectaShell$TrifectaConsole.shell(TrifectaShell.scala:114)
        at com.github.ldaniels528.trifecta.TrifectaShell$.main(TrifectaShell.scala:61)
        at com.github.ldaniels528.trifecta.TrifectaShell.main(TrifectaShell.scala)

**Comment by ldaniels528** [comment]
I'd like you to try one more thing...

sbt "project trifecta_cli" run

This will run the binaries without creating a fat jar. I suspect when the jar file is being created that the org.fusesource.jansi.internal.Kernel32 class is being corrupted.
