### ISSUE TITLE
Query window default should enclose topic names in quotes when the name contains non-alphanumeric characters

### ISSUE THREAD

**Issue by andrew-rosca** [ldaniels528/trifecta#37]
If the topic name contains non-alphanumeric characters (such as dash) the query window generates an error:
```
play.api.UnexpectedException: Unexpected exception[IllegalArgumentException: Illegal argument at "ct * from topic" near "select * from topic" (position 19)]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:250) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.mvc.WithFilters.onError(Filters.scala:93) [com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2.11-2.4.0.jar:2.4.0]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [com.typesafe.play.play-netty-server_2.11-2.4.0.jar:2.4.0]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: java.lang.IllegalArgumentException: Illegal argument at "ct * from topic" near "select * from topic" (position 19)
	at com.github.ldaniels528.trifecta.messages.query.parser.KafkaQueryTokenizer.parse(KafkaQueryTokenizer.scala:31) ~[com.github.ldaniels528.trifecta-core-0.22.0rc8b.jar:0.22.0rc8b]
	at com.github.ldaniels528.trifecta.messages.query.parser.KafkaQueryTokenizer$.parse(KafkaQueryTokenizer.scala:130) ~[com.github.ldaniels528.trifecta-core-0.22.0rc8b.jar:0.22.0rc8b]
	at com.github.ldaniels528.trifecta.messages.query.parser.KafkaQueryParser$.apply(KafkaQueryParser.scala:24) ~[com.github.ldaniels528.trifecta-core-0.22.0rc8b.jar:0.22.0rc8b]
	at com.github.ldaniels528.trifecta.ui.controllers.KafkaPlayRestFacade.executeQuery(KafkaPlayRestFacade.scala:93) ~[com.github.ldaniels528.trifecta-ui-0.22.0rc8b-0.10.1.0.jar:0.22.0rc8b-0.10.1.0]
	at com.github.ldaniels528.trifecta.ui.controllers.QueryController$$anonfun$executeQuery$1.apply(QueryController.scala:21) ~[com.github.ldaniels528.trifecta-ui-0.22.0rc8b-0.10.1.0.jar:0.22.0rc8b-0.10.1.0]
	at com.github.ldaniels528.trifecta.ui.controllers.QueryController$$anonfun$executeQuery$1.apply(QueryController.scala:18) ~[com.github.ldaniels528.trifecta-ui-0.22.0rc8b-0.10.1.0.jar:0.22.0rc8b-0.10.1.0]
	at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
```

To resolve this, the topic name must be enclosed in quotes.

This is not immediately obvious. Right now by default the query window is populated with an example query as follows:
`select * from topic-name with default`

which will not work. 

Enclose the topic name in quotes when the topic name contains non-alphanumeric characters
`select * from "topic-name" with default`

It would also be useful to mention this caveat in the Hints & Tips panel.

**Comment by andrew-rosca** [comment]
Duh, duplicate of #34
