### ISSUE TITLE
unable to inspect brokers

### ISSUE THREAD

**Issue by federated-life** [ldaniels528/trifecta#7]
whats the correct config for config.properties to connect to brokers? seems that even though the data is in the id, that it doesn't show up in the ui.

zk:/> kbrokers
Runtime error: KeeperErrorCode = NoNode for /brokers/ids

zk:/> ztree /kafka/brokers/ids
+ ----------------------------------------------- +
| path                    creationTime            |
+ ----------------------------------------------- +
| /kafka/brokers/ids      01/18/15 08:52:53 CST   |
| /kafka/brokers/ids/642  02/17/15 05:39:43 CST   |
| /kafka/brokers/ids/643  02/17/15 05:39:43 CST   |
| /kafka/brokers/ids/641  02/17/15 05:39:44 CST   |
+ ----------------------------------------------- +
zk:/> 

{
    "jmx_port": -1,
    "timestamp": "1424216383325",
    "host": "hostname.of.real.host",
    "version": 1,
    "port": 9092
}

**Comment by ldaniels528** [comment]
Trifecta is looking for the Kafka brokers under "/brokers/ids"; however, in your case it's "/kafka/brokers/ids". I guess I need to create a property for specifying the root of the tree; in your case it would be "/kafka" instead of "/". I'll do that and let you know when it's checked in.

**Comment by ldaniels528** [comment]
Could you issue the following commands in Trifecta:

zcd /kafka
zls

And send me the results?

**Comment by ldaniels528** [comment]
Please try the code in branch scala_2.11-0.8.2-beta and add the following property to your config:

trifecta.zookeeper.kafka.brokers.path = /kafka/brokers

**Comment by federated-life** [comment]
still is not picking up the brokers / topics after setting:
trifecta.zookeeper.kafka.brokers.path = /kafka/brokers


+ ----------------------------------------- +
| path              creationTime            |
+ ----------------------------------------- +
| consumers         01/18/15 08:52:53 CST   |
| config            01/18/15 08:52:53 CST   |
| controller        03/03/15 01:23:20 CST   |
| brokers           01/18/15 08:52:53 CST   |
| admin             01/18/15 08:52:53 CST   |
| controller_epoch  01/18/15 08:52:53 CST   |
+ ----------------------------------------- +
zk:/kafka> zcd /kafka/brokers
zk:/kafka/brokers> zls
+ ------------------------------- +
| path    creationTime            |
+ ------------------------------- +
| topics  01/18/15 08:52:53 CST   |
| ids     01/18/15 08:52:53 CST   |
+ ------------------------------- +
zk:/kafka/brokers> zcd /kafka/brokers/ids
zk:/kafka/brokers/ids> zls
+ ----------------------------- +
| path  creationTime            |
+ ----------------------------- +
| 642   03/03/15 01:23:20 CST   |
| 643   03/03/15 01:23:20 CST   |
| 641   03/03/15 01:23:20 CST   |
+ ----------------------------- +
zk:/kafka/brokers/ids>

**Comment by ldaniels528** [comment]
Okay, I've updated the branch and I think this version will work for you. Set the following in your config and let me know if you have any issues:

trifecta.zookeeper.kafka.root.path = /kafka

**Comment by ldaniels528** [comment]
For your convenience, I've published a pre-released binary version (v0.18.16-beta1) with the multi-tenant support you require.

https://github.com/ldaniels528/trifecta/releases

**Comment by federated-life** [comment]
Im stilling hitting an issue in changing the path.


2015-03-03 17:27:00 ERROR WebContentActor:47 - Resource '/rest/getTopicSummaries' failed unexpectedly
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
	at com.ldaniels528.trifecta.io.zookeeper.ZkProxyCurator.getChildren(ZkProxyCurator.scala:68)
	at com.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$.getBrokerList(KafkaMicroConsumer.scala:355)
	at com.ldaniels528.trifecta.rest.KafkaRestFacade.com$ldaniels528$trifecta$rest$KafkaRestFacade$$brokers$lzycompute(KafkaRestFacade.scala:65)
	at com.ldaniels528.trifecta.rest.KafkaRestFacade.com$ldaniels528$trifecta$rest$KafkaRestFacade$$brokers(KafkaRestFacade.scala:65)
	at com.ldaniels528.trifecta.rest.KafkaRestFacade$$anonfun$getTopicSummaries$1.apply(KafkaRestFacade.scala:491)
	at com.ldaniels528.trifecta.rest.KafkaRestFacade$$anonfun$getTopicSummaries$1.apply(KafkaRestFacade.scala:507)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
2015-03-03 17:27:00 ERROR WebContentActor:47 - Resource '/rest/getConsumerDetails' failed unexpectedly
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /consumers
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
	at com.ldaniels528.trifecta.io.zookeeper.ZkProxyCurator.getChildren(ZkProxyCurator.scala:68)
	at com.ldaniels528.trifecta.io.kafka.KafkaMicroConsumer$.getConsumerDetails(KafkaMicroConsumer.scala:371)
	at com.ldaniels528.trifecta.rest.KafkaRestFacade$$anonfun$getConsumerGroupsNative$1.apply(KafkaRestFacade.scala:276)
	at com.ldaniels528.trifecta.rest.KafkaRestFacade$$anonfun$getConsumerGroupsNative$1.apply(KafkaRestFacade.scala:276)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by ldaniels528** [comment]
Is this issue happening for both the command line interface and the web application?

**Comment by federated-life** [comment]
actually, I was using the wrong param, when I used the latest one, it appears to work!

trifecta.zookeeper.kafka.root.path

thanks  !

**Comment by ldaniels528** [comment]
:-) Great! I'll close the issue. Enjoy!

**Comment by cyrilmathew** [comment]
Hello Im also facing the issue

From commandline, this is working

curl localhost:9000/api/broker
[{"host":"XX.XX.X.XX","port":9092,"brokerId":0},{"host":"XX.XX.X.XX","port":9092,"brokerId":0}]

But in the UI (Screenshot also attached)

################
 No brokers were found.
This usually means that either:
Kafka has not been setup on the Zookeeper node for which you are pointing.
Or, Trifecta has not been configured to point to the Zookeeper instance that is running Kafka.
#################

###########################
cat config.properties

trifecta.web.host = 0.0.0.0
trifecta.web.port = 9000

trifecta.zookeeper.host = XX.XX.X.XX:2181
trifecta.web.push.interval.consumer = 15
trifecta.web.push.interval.sampling = 2
trifecta.web.push.interval.topic = 15
trifecta.zookeeper.kafka.root.path = /logging
trifecta.web.actor.concurrency = 10
##############################

<img width="1030" alt="screen shot 2018-02-26 at 7 26 36 pm" src="https://user-images.githubusercontent.com/30928292/36674061-ff92ecf6-1b2a-11e8-9b71-2562373e5fb8.png">
